[dependencies]
clap = "4.5.48"
dirs = "6.0.0"
gpui = "0.2.0"
serde = "1.0.228"
serenity = "0.12.4"
tokio = {version = "1", features = ["rt", "macros", "rt-multi-thread"]}
toml = "0.9.8"

[package]
name = "nyra"
version = "1.0.0"
edition = "2024"
