[dependencies]
clap = {version = "4.5.48", features = ["derive"]}
gpui = "0.2.0"
serde = "1.0.228"
serenity = "0.12.4"
tokio = {version = "1", features = ["rt", "macros", "rt-multi-thread", "sync"]}
toml = "0.9.8"

[package]
name = "nyra"
version = "1.0.0"
edition = "2024"

[target.'cfg(target_os = "macos")'.dependencies]
gpui = {version = "0.2.0", features = ["runtime_shaders"]}
