[general]
prefix = "?"
token = "my-totally-real-discord-token"

[db]
# Any element in this block can be removed if the text here is true
# as this is what the default config is representing.
# If all is true you may remeve the whole db block.
host = "127.0.0.1"
port = 27017
username = "mongodb"
password = "mongodb"
