[dependencies]
gpui = "*"
libloading = "0.8.9"
tokio = {version = "1", features = ["rt", "macros"]}

[lib]
name = "nyra_gui"
crate-type = ["cdylib"]

[package]
name = "nyra_gui"
version = "0.1.0"
edition = "2024"
